"""empty message

Revision ID: bae3d41e6892
Revises: 
Create Date: 2026-01-31 09:14:45.889461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bae3d41e6892'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('daily_token_limit', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('tokens_used_today', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tokens_used_today')
    op.drop_column('users', 'daily_token_limit')
    # ### end Alembic commands ###
